version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        restart: always # we always want this service to run
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80' # Port outside the container:Inside the container
    api:
        build:
            dockerfile: Dockerfile.dev # Only for the name, dont need dir yet
            context: ./server
        volumes:
            - /app/node_modules # Don't override folder in container
            - ./server:/app # Look at server dir and copy everything into /app
        environment: # Most of these can be found in the docs
            - REDIS_HOST=redis
            - REDIS_PORT=6379 # Can be found on dockerhub docs, EXPOSE port
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORDS=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        
